apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: ai-platform
  labels:
    app.kubernetes.io/part-of: ai-platform
    app.kubernetes.io/component: namespace-security
automountServiceAccountToken: false
