apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - http-redirect.yaml
  - securitypolicy.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml

configMapGenerator:
  - name: ai-platform-api-oidc-ca
    namespace: ai-platform
    files:
      - ca.crt=certs/auth-ai-platform-root-ca.crt

generatorOptions:
  disableNameSuffixHash: true
