apiVersion: v1
kind: Service
metadata:
  name: ai-platform-api
  namespace: ai-platform
  labels:
    app.kubernetes.io/name: ai-platform-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ai-platform
spec:
  selector:
    app.kubernetes.io/name: ai-platform-api

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http

  type: ClusterIP
