---
apiVersion: platform.anselem.dev/v1alpha1
kind: ModelService
metadata:
  name: iris-v1-operator
  namespace: ai-platform
spec:
  backend: KServe
  replicas: 1

  predictor:
    modelFormat:
      name: sklearn
      version: "1"

    runtime: kserve-sklearnserver
    storageUri: s3://models/sklearn/iris/v1
    serviceAccountName: kserve-model-reader

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
