name: E2E Tests

on:
  push:
  pull_request:

permissions: {}

jobs:
  test-e2e:
    permissions:
      contents: read
    name:  E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Install kind
        shell: bash
        run: |
          set -euo pipefail

          KIND_VERSION="v0.32.0"
          ARCH="$(go env GOARCH)"

          curl -fsSLO \
            "https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-${ARCH}"

          curl -fsSLO \
            "https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-${ARCH}.sha256sum"

          sha256sum -c "kind-linux-${ARCH}.sha256sum"

          chmod +x "kind-linux-${ARCH}"
          sudo mv "kind-linux-${ARCH}" /usr/local/bin/kind

          kind version

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e
